### ISSUE TITLE
Buttons in choice selection is broken

### ISSUE THREAD

**Issue by AlexProfanov** [anonl/nvlist#46]
Very simple code:
function main()
  choice("Spaces shall not pass", "And they will not")
end
And result:
![_2017-05-08_20-56-42](https://cloud.githubusercontent.com/assets/24699663/25813045/a20a61e4-3431-11e7-9b87-833a86ff893b.png)
I tried to locate issue, and it seems to be somewhere in Java code, somewhere in TextRenderer or even further. I don't want to dig down, so just reporting this issue to you. This happens with unicode spaces (0x00A0, 0x2000, etc) too and even with dash ('-') character. Replacing spaces with underscores ('_') helps.

**Comment by anonl** [comment]
Thank you very much for the bug report.
